import { escape as e } from './lib.mjs';
import { icon, inquiry } from './components.mjs';
import { cities, cityPath } from './data/cities.mjs';
import { guides, guidePath } from './data/guides.mjs';

const sourceLink = source => `<a href="${e(source.url)}" target="_blank" rel="noopener noreferrer">${e(source.label)}</a>`;
const paragraph = text => `<p>${e(text)}</p>`;
const displayDate = date => date.split('-').reverse().join('/');
const guideCredit = (config, guide) => guide.reviewed ? `<p class="source-note">Conteúdo editorial de <a href="/contato/#editorial">${e(config.brand)}</a>. Revisado em <time datetime="${e(guide.reviewed)}">${displayDate(guide.reviewed)}</time>. <a href="/contato/">Informe uma correção ou consulte o atendimento</a>.</p>` : '';
const guideSources = guide => guide.sources?.length ? `<section id="fontes"><h2>Fontes e limites deste guia</h2><p>Referências consultadas em ${displayDate(guide.reviewed)} para as orientações identificadas no texto:</p><ul>${guide.sources.map(source => `<li>${sourceLink(source)}</li>`).join('')}</ul><p>As fichas e contas são exemplos de planejamento. Essas fontes não confirmam catálogo, estoque, preços, entrega ou vínculo com a Cestas Populares. Para um pedido, confirme os detalhes no <a href="/contato/">atendimento comercial</a>.</p></section>` : '';
const crumbs = (parent, title) => `<nav class="breadcrumbs" aria-label="Caminho da página"><a href="/">Início</a><span aria-hidden="true">/</span>${parent ? `<a href="${parent.path}">${e(parent.title)}</a><span aria-hidden="true">/</span>` : ''}<span aria-current="page">${e(title)}</span></nav>`;
const hero = (label, title, intro, parent, shortTitle, extra = '') => `<section class="page-hero editorial-hero"><div class="container">${crumbs(parent, shortTitle || title)}<span class="eyebrow">${e(label)}</span><h1>${e(title)}</h1><p>${e(intro)}</p>${extra}</div></section>`;
export const guideCards = (selected = guides) => `<div class="resource-grid">${selected.map(guide => `<article class="resource-card"><span class="resource-icon">${icon(guide.icon)}</span><span class="eyebrow">${e(guide.category)}</span><h3><a href="${guidePath(guide.slug)}">${e(guide.title)}</a></h3><p>${e(guide.description)}</p><a class="text-link" href="${guidePath(guide.slug)}" aria-label="Ler: ${e(guide.title)}">Ler o guia ${icon('arrow')}</a></article>`).join('')}</div>`;
const cityCards = selected => `<div class="city-directory">${selected.map(city => `<a class="city-card" href="${cityPath(city.slug)}"><span class="city-card-name">${icon('pin')}${e(city.name)}</span><span>${e(city.localTitle)}</span><span class="city-card-action">Ver orientações ${icon('arrow')}</span></a>`).join('')}</div>`;

export function editorialPages(config, catalog) {
  const cityParent = { path: '/cidades/', title: 'Cidades' };
  const guideParent = { path: '/guias/', title: 'Guias' };
  const localPages = cities.map(city => ({
    path: cityPath(city.slug), title: `Cestas básicas em ${city.name}`, description: city.description, parent: cityParent,
    body: `${hero(city.additional ? 'CONSULTA EM VITÓRIA DE SANTO ANTÃO' : 'COMPRA E ENTREGA NA SUA CIDADE', `Cestas básicas em ${city.name}`, city.intro, cityParent, city.name, '<a class="button button-primary editorial-action" href="#consulta">Preparar consulta de entrega ' + icon('arrow') + '</a>')}
    <section class="section"><div class="container local-layout"><article class="prose local-article"><div class="coverage-note"><strong>Atendimento sob consulta.</strong> Confirme disponibilidade, frete e prazo para seu endereço. Esta página não representa uma filial ou ponto de retirada.</div>
    <section id="localidade"><h2>${e(city.localTitle)}</h2>${paragraph(city.local)}<p class="source-note">Referência de localização: ${sourceLink(city.source)}. Consultada em 12/09/2026.</p>${city.paragraphs.map(paragraph).join('')}</section>
    <section id="planejamento"><h2>${e(city.taskTitle)}</h2>${paragraph(city.task)}</section>
    <section id="passo-a-passo"><h2>Como preparar sua compra</h2><ol class="tutorial-steps">${city.steps.map(([title, text]) => `<li><h3>${e(title)}</h3>${paragraph(text)}</li>`).join('')}</ol><p>Para conferir itens e pagamento, siga também o <a href="/como-comprar/">passo a passo completo de compra</a>.</p></section>
    <section id="duvidas"><h2>Dúvidas sobre a consulta em ${e(city.name)}</h2><div class="faq">${city.faq.map(([question, answer]) => `<details><summary>${e(question)}${icon('plus')}</summary>${paragraph(answer)}</details>`).join('')}</div></section>
    </article><aside class="local-consult" id="consulta" aria-label="Consulta de cestas para ${e(city.name)}">${inquiry(config, catalog, 'a composição e a entrega para meu endereço', { city: city.name })}<div class="aside-links"><h2>Continue sua consulta</h2><a href="/cestas-basicas/">Composição e orçamento</a><a href="${guidePath(city.guide)}">${e(guides.find(guide => guide.slug === city.guide).title)}</a><a href="/guias/como-vender-cestas-basicas/">Como começar a vender cestas</a></div></aside></div></section>
    <section class="section section-cream"><div class="container"><div class="section-heading"><span class="eyebrow">OUTRO DESTINO?</span><h2>Consulte a cidade de quem vai receber.</h2><p>Escolha a página correspondente ao endereço. A confirmação de uma localidade não se estende automaticamente às demais.</p></div>${cityCards(city.nearby.map(slug => cities.find(item => item.slug === slug)))}<a class="text-link section-more" href="/cidades/">Ver todas as cidades ${icon('arrow')}</a></div></section>`
  }));
  const guidePages = guides.map(guide => ({
    path: guidePath(guide.slug), title: guide.title, description: guide.description, parent: guideParent,
    ...(guide.reviewed ? { lastModified: guide.reviewed, article: { modified: guide.reviewed, sources: guide.sources } } : {}),
    body: `${hero(guide.category.toUpperCase(), guide.title, guide.intro, guideParent, guide.title, guideCredit(config, guide))}<section class="section"><div class="container reading-layout"><nav class="reading-toc" aria-label="Neste guia"><strong>Neste guia</strong>${guide.sections.map(section => `<a href="#${section.id}">${e(section.title)}</a>`).join('')}${guide.sources?.length ? '<a href="#fontes">Fontes e limites</a>' : ''}<span>Atualizado em ${displayDate(guide.reviewed || '2026-09-12')}</span></nav><article class="prose guide-article">${guide.sections.map(section => `<section id="${section.id}"><h2>${e(section.title)}</h2>${section.html}</section>`).join('')}${guideSources(guide)}<div class="article-next"><h2>Próximo passo</h2><p>Com a lista organizada, veja como consultar uma compra e escolha a cidade de recebimento.</p><a class="button button-primary" href="/como-comprar/">Como comprar ${icon('arrow')}</a><a class="text-link" href="/cidades/">Consultar minha cidade</a></div></article></div></section><section class="section section-cream"><div class="container"><div class="section-heading"><span class="eyebrow">CONTINUE A LEITURA</span><h2>Mais orientações para sua cesta.</h2></div>${guideCards(guide.related.map(slug => guides.find(item => item.slug === slug)))}</div></section>`
  }));
  return [{
    path: '/cidades/', title: 'Cestas básicas por cidade em Recife e região', description: 'Escolha sua cidade para consultar cestas básicas. Guias locais para os 14 municípios da Região Metropolitana do Recife e Vitória de Santo Antão.',
    body: `${hero('ENCONTRE SUA CIDADE', 'Sua cesta começa pelo endereço certo.', 'Veja orientações de compra e recebimento para cada cidade. Prepare bairro, localidade e quantidade desejada antes de consultar o atendimento.', null, 'Cidades')}<section class="section"><div class="container"><div class="coverage-note"><strong>Entrega depende de confirmação.</strong> As páginas abaixo ajudam a organizar sua consulta. Não há frete, prazo ou cobertura garantidos para todo o município.</div><div class="directory-intro"><h2>Recife e Região Metropolitana</h2><p>Os 14 municípios aparecem na organização oficial da Região Metropolitana. Vitória de Santo Antão fica na seção adicional abaixo. <a href="https://www.tre-pe.jus.br/comunicacao/noticias/2026/Julho/regiao-metropolitana-do-recife-concentra-41-7-do-eleitorado-de-pernambuco" target="_blank" rel="noopener noreferrer">Confira a referência do TRE-PE</a>.</p></div>${['Recife', 'Norte', 'Oeste', 'Sul'].map(group => `<section class="directory-group"><h3>${group === 'Recife' ? 'Recife' : `Eixo ${group.toLowerCase()}`}</h3>${cityCards(cities.filter(city => city.group === group))}</section>`).join('')}<section class="directory-group additional-directory"><h2>Também: Vitória de Santo Antão</h2><p>Cidade adicional à Região Metropolitana, com consulta específica de entrega.</p>${cityCards(cities.filter(city => city.additional))}</section><div class="article-next"><h2>Não sabe por onde começar?</h2><p>Prepare a lista de alimentos, confira as quantidades e compare o orçamento com entrega.</p><a class="text-link" href="/guias/">Explorar os guias ${icon('arrow')}</a></div></div></section>`
  }, {
    path: '/guias/', title: 'Guias de cestas básicas: comprar, montar e vender', description: 'Tutoriais para montar uma cesta básica, conferir alimentos, comparar preços, comprar em grupo e planejar a venda de cestas.',
    body: `${hero('DA LISTA À MESA', 'Guias para comprar melhor e aprender a vender.', 'Passo a passo, listas de conferência e exemplos para planejar sua cesta. Escolha o assunto que ajuda na sua próxima decisão.', null, 'Guias')}<section class="section"><div class="container"><div class="guide-start"><span>${icon('chat')}</span><div><h2>É sua primeira compra por aqui?</h2><p>Veja como consultar as opções, revisar o orçamento e combinar o recebimento pelo WhatsApp.</p></div><a class="button button-primary" href="/como-comprar/">Como comprar ${icon('arrow')}</a></div>${guideCards()}</div></section><section class="section section-cream"><div class="container split-section"><div><span class="eyebrow">INFORMAÇÃO LOCAL</span><h2>Consulte o destino da sua compra.</h2><p>Encontre orientações para informar bairro, distrito e ponto de recebimento na sua cidade.</p><a class="text-link" href="/cidades/">Escolher uma cidade ${icon('arrow')}</a></div><div class="payment-note"><h3>Informação para decidir com clareza</h3><p>Os exemplos dos guias são educativos. Composição, preços, pagamento e entrega da Cestas Populares devem ser confirmados no atendimento.</p><a class="text-link" href="/cestas-basicas/">Consultar as opções ${icon('arrow')}</a></div></div></section>`
  }, ...localPages, ...guidePages];
}
