import { contactButton, icon, sectionTitle, steps, callout, catalogCards, paymentDetails, plannedCities } from './components.mjs';
import { escape as e } from './lib.mjs';
export function pages(config, catalog) {
  return [{ path: '/', title: 'Cestas básicas em Recife', description: 'Consulte cestas básicas em Recife, Olinda, Jaboatão e Região Metropolitana. Conheça as opções e consulte pagamento e entrega pelo WhatsApp.', body: `
  <section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow"><span class="eyebrow-line"></span> O ESSENCIAL, PERTO DE VOCÊ</span><h1>Cestas básicas<br>em Recife <em>e região.</em></h1><p>Alimentos para o dia a dia da sua família. Consulte nossas cestas básicas, as formas de pagamento e a entrega para sua cidade pelo WhatsApp.</p><div class="hero-actions"><a class="button button-primary" href="/cestas-basicas/">Conheça nossas cestas ${icon('arrow')}</a><a class="text-link" href="/como-comprar/">Como funciona</a></div><div class="hero-note">${icon('chat')} Atendimento de gente para gente, pelo WhatsApp.</div></div><figure class="hero-visual"><img src="/assets/cesta-grande.webp" srcset="/assets/cesta-grande-560.webp 560w, /assets/cesta-grande.webp 1024w" sizes="(max-width: 600px) 92vw, 45vw" width="1024" height="1024" alt="Cesta grande ilustrativa com carnes embaladas, refrigerantes, arroz, feijão e outros alimentos" fetchpriority="high"><div class="image-label">${icon('basket')} Variedade para a mesa da família.</div><figcaption>Imagem ilustrativa. Não representa a composição de uma cesta à venda.</figcaption></figure></div></section>
  <div class="benefits"><div class="container benefits-grid"><div>${icon('basket')}<span>Alimentos para o dia a dia</span></div><div>${icon('chat')}<span>Consulta pelo WhatsApp</span></div><div>${icon('pin')}<span>Entrega sob consulta</span></div></div></div>
  <section class="section"><div class="container">${sectionTitle('NOSSAS CESTAS', 'Cestas básicas para<br>abastecer a sua casa.', 'Consulte as opções disponíveis e encontre a cesta que faz sentido para você.')} ${catalogCards(config, catalog, 3)}</div></section>
  <section class="section section-cream"><div class="container">${sectionTitle('DO SEU JEITO', 'Comprar começa com uma conversa.')} ${steps()}<a class="text-link" href="/como-comprar/">Veja como comprar ${icon('arrow')}</a></div></section>
  <section class="section"><div class="container split-section"><div><span class="eyebrow">CADA COMPRA, BEM COMBINADA</span><h2>Condições claras.<br>Você decide com calma.</h2><p>Conheça as opções de pagamento disponíveis e confira o valor total da sua compra com o atendimento.</p><a class="text-link" href="/condicoes-de-compra/">Condições de compra ${icon('arrow')}</a></div><div class="payment-note">${icon('wallet')}<h3>Vamos falar sobre pagamento?</h3>${paymentDetails(config)}${contactButton(config, 'Consultar pagamento', { topic: 'as formas de pagamento disponíveis' }, 'button-outline')}</div></div></section>
  <section class="delivery-band"><div class="container split-section"><div><span class="eyebrow">PERTO DA SUA MESA</span><h2>Entrega de cestas básicas<br>na sua região.</h2><p>Informe sua cidade e bairro para consultar a possibilidade de atendimento, o frete e o prazo.</p><a class="button button-cream" href="/entregas/">Consultar minha região ${icon('arrow')}</a></div><div class="region-card">${icon('pin')}<span class="eyebrow">${config.delivery.confirmedCities.length ? 'CIDADES ATENDIDAS' : 'REGIÃO DE INTERESSE'}</span><h3>${config.delivery.confirmedCities.length ? e(config.delivery.confirmedCities.join(', ')) : 'Recife, Região Metropolitana<br>e Vitória de Santo Antão'}</h3><p>${config.delivery.confirmedCities.length ? 'Consulte seu bairro ou CEP para confirmar frete e prazo.' : 'Cobertura em confirmação. O atendimento depende da sua localização.'}</p><span class="region-foot">Cada entrega é combinada com você.</span></div></div><div class="container">${plannedCities(config, true)}</div></section>
  <section class="section"><div class="container faq-grid"><div><span class="eyebrow">SEM FICAR NA DÚVIDA</span><h2>Bom saber<br>antes de comprar.</h2><p>Não encontrou sua resposta?<br><a class="text-link" href="/contato/">Fale com a gente ${icon('arrow')}</a></p></div><div class="faq"><details><summary>Como vejo os itens e o valor da cesta? ${icon('plus')}</summary><p>Consulte as opções com o atendimento. Antes de comprar, confirme a composição, as quantidades, a disponibilidade e o valor total.</p></details><details><summary>Vocês entregam no meu bairro? ${icon('plus')}</summary><p>Informe sua cidade e bairro pelo WhatsApp. A possibilidade de entrega, o frete e o prazo precisam ser confirmados para cada endereço.</p></details><details><summary>Quais são as formas de pagamento? ${icon('plus')}</summary><p>Fale com o atendimento para conhecer as opções disponíveis e as condições de cada modalidade.</p></details><details><summary>A consulta no WhatsApp já faz um pedido? ${icon('plus')}</summary><p>Não. A conversa começa como uma consulta. O pedido só é combinado depois de você conferir e aceitar os itens, o valor, o pagamento e a entrega.</p></details></div></div></section>${callout(config)}` }];
}
